/**
 * events.js
 * * Dit bestand fungeert als de 'database' voor de website.
 * Alle informatie over de buitenbioscoop-evenementen staat hier in een gestructureerd formaat.
 * Om de site aan te passen, hoef je alleen dit bestand te wijzigen.
 * * Hoe een evenement aan te passen:
 * - Zoek het evenement in de 'events' array hieronder.
 * - Wijzig de waarden van de velden (bv. 'title', 'period', 'location').
 * - Om een film toe te voegen, voeg een nieuw object toe aan de 'program' array.
 * * Hoe een evenement toe te voegen:
 * - Kopieer een bestaand evenement-object (alles van het eerste '{' tot het laatste '}').
 * - Plak het aan het einde van de lijst (vóór de laatste ']').
 * - Pas alle informatie aan voor het nieuwe evenement. Zorg voor een unieke 'id'.
 * * Hoe een evenement te verwijderen:
 * - Verwijder het volledige object van het evenement uit de array.
 */
const filmDatabase = {
    "10 Things I Hate About You": { year: 1999, lang: "Engels", country: "VS", duration: 97, genres: ["Komedie", "Drama", "Romantiek"] },
    "7 Years in Tibet": { year: 1997, lang: "Engels", country: "VS", duration: 136, genres: ["Avontuur", "Biografie", "Drama"] },
    "A Bright Future": { year: 2025, lang: "Spaans", country: "Duitsland, Uruguay, Argentinië", duration: 98, genres: ["Sciencefiction"] },
    "A Man Called Otto": { year: 2022, lang: "Engels", country: "VS", duration: 126, genres: ["Komedie", "Drama"] },
    "A Vida Luminosa": { year: 2025, lang: "Portugees", country: "Portugal", duration: 106, genres: ["Drama"] },
    "About a Boy": { year: 2002, lang: "Engels", country: "VK", duration: 101, genres: ["Komedie", "Drama", "Romantiek"] },
    "Amélie": { year: 2001, lang: "Frans", country: "Frankrijk", duration: 122, genres: ["Komedie", "Romantiek"] },
    "Amsterdam": { year: 2022, lang: "Engels", country: "VS", duration: 134, genres: ["Komedie", "Drama", "Historie"] },
    "Anora": { year: 2024, lang: "Engels, Russisch", country: "VS", duration: 139, genres: ["Komedie", "Drama", "Romantiek"] },
    "Billy Elliot": { year: 2000, lang: "Engels", country: "VK", duration: 110, genres: ["Drama", "Muziek"] },
    "Bitter Gold": { year: 2024, lang: "Spaans", country: "Duitsland, Uruguay, Chili", duration: 83, genres: ["Neowestern", "Thriller", "Drama"] },
    "Bohemian Rhapsody": { year: 2018, lang: "Engels", country: "VK", duration: 134, genres: ["Biografie", "Drama", "Muziek"] },
    "Bridget Jones's Diary": { year: 2001, lang: "Engels", country: "VK", duration: 97, genres: ["Komedie", "Drama", "Romantiek"] },
    "Brother Verses Brother": { year: 2025, lang: "Engels", country: "VS", duration: 91, genres: ["Komedie", "Drama", "Muziek"] },
    "Caro Diario": { year: 1993, lang: "Italiaans", country: "Italië", duration: 100, genres: ["Komedie", "Drama"] },
    "Catch Me If You Can": { year: 2002, lang: "Engels", country: "VS", duration: 141, genres: ["Biografie", "Misdaad", "Drama"] },
    "Challengers": { year: 2024, lang: "Engels", country: "VS", duration: 131, genres: ["Komedie", "Drama", "Romantiek"] },
    "Dirty Dancing": { year: 1987, lang: "Engels", country: "VS", duration: 100, genres: ["Drama", "Muziek", "Romantiek"] },
    "Do the Right Thing": { year: 1989, lang: "Engels", country: "VS", duration: 120, genres: ["Komedie", "Drama"] },
    "Ex Machina": { year: 2014, lang: "Engels", country: "VK", duration: 108, genres: ["Sci-Fi", "Drama", "Thriller"] },
    "Fantastic Mr. Fox": { year: 2009, lang: "Engels", country: "VS", duration: 87, genres: ["Animatie", "Avontuur", "Komedie"] },
    "Fatma": { year: 1960, lang: "Turks", country: "Turkije", duration: 105, genres: ["Drama", "Romantiek"]},
    "Flow": { year: 2024, lang: "Geen dialoog", country: "Letland, Frankrijk, België", duration: 84, genres: ["Animatie", "Avontuur", "Familie"] },
    "Forrest Gump": { year: 1994, lang: "Engels", country: "VS", duration: 142, genres: ["Drama", "Romantiek"] },
    "Fwends": { year: 2025, lang: "Engels, Frans", country: "Australië", duration: 92, genres: ["Komedie"] },
    "Ghost In The Shell": { year: 1995, lang: "Japans", country: "Japan", duration: 83, genres: ["Animatie", "Actie", "Sci-Fi"] },
    "Gloria!": { year: 2024, lang: "Italiaans", country: "Italië", duration: 100, genres: ["Historie", "Muziek"] },
    "Grease": { year: 1978, lang: "Engels", country: "VS", duration: 110, genres: ["Musical", "Romantiek"] },
    "Green Book": { year: 2018, lang: "Engels", country: "VS", duration: 130, genres: ["Biografie", "Komedie", "Drama"] },
    "Hababam Sınıfı": { year: 1975, lang: "Turks", country: "Turkije", duration: 87, genres: ["Komedie", "Drama"] },
    "Her": { year: 2013, lang: "Engels", country: "VS", duration: 126, genres: ["Drama", "Romantiek", "Sci-Fi"] },
    "In the Heights": { year: 2021, lang: "Engels", country: "VS", duration: 143, genres: ["Drama", "Musical", "Romantiek"] },
    "Interstellar": { year: 2014, lang: "Engels", country: "VS", duration: 169, genres: ["Avontuur", "Drama", "Sci-Fi"] },
    "Into the Wild": { year: 2007, lang: "Engels", country: "VS", duration: 148, genres: ["Avontuur", "Biografie", "Drama"] },
    "Ja Zuster, Nee Zuster": { year: 2002, lang: "Nederlands", country: "Nederland", duration: 104, genres: ["Komedie", "Muzikaal"] },
    "Kabhi Khushi Kabhie Gham": { year: 2001, lang: "Hindi", country: "India", duration: 210, genres: ["Drama", "Musical", "Romantiek"] },
    "Kneecap": { year: 2024, lang: "Iers, Engels", country: "Ierland", duration: 105, genres: ["Biografie", "Komedie", "Drama"] },
    "Kontinental ’25": { year: 2025, lang: "Roemeens, Hongaars, Duits", country: "Roemenië", duration: 109, genres: ["Komedie-drama"] },
    "La Chimera": { year: 2023, lang: "Italiaans", country: "Italië", duration: 130, genres: ["Avontuur", "Komedie", "Drama"] },
    "La La Land": { year: 2016, lang: "Engels", country: "VS", duration: 128, genres: ["Komedie", "Drama", "Musical"] },
    "La vita è bella": { year: 1997, lang: "Italiaans", country: "Italië", duration: 116, genres: ["Komedie", "Drama", "Romantiek"] },
    "Lion": { year: 2016, lang: "Engels", country: "Australië", duration: 118, genres: ["Biografie", "Drama"] },
    "Life of Pi": { year: 2012, lang: "Engels", country: "VS", duration: 127, genres: ["Avontuur", "Drama", "Fantasy"] },
    "Little Miss Sunshine": { year: 2006, lang: "Engels", country: "VS", duration: 101, genres: ["Komedie", "Drama"] },
    "Lost in Translation": { year: 2003, lang: "Engels", country: "VS", duration: 102, genres: ["Komedie", "Drama"] },
    "Mamma Mia!": { year: 2008, lang: "Engels", country: "VS", duration: 108, genres: ["Komedie", "Musical", "Romantiek"] },
    "Mean Girls": { year: 2004, lang: "Engels", country: "VS", duration: 97, genres: ["Komedie"] },
    "Midnight in Paris": { year: 2011, lang: "Engels", country: "VS", duration: 94, genres: ["Komedie", "Fantasy", "Romantiek"] },
    "Mrs. Doubtfire": { year: 1993, lang: "Engels", country: "VS", duration: 125, genres: ["Komedie", "Drama", "Familie"] },
    "No Country for Old Men": { year: 2007, lang: "Engels", country: "VS", duration: 122, genres: ["Misdaad", "Drama", "Thriller"] },
    "Notting Hill": { year: 1999, lang: "Engels", country: "VK", duration: 124, genres: ["Komedie", "Drama", "Romantiek"] },
    "On the Road": { year: 2012, lang: "Engels", country: "VS", duration: 124, genres: ["Avontuur", "Drama", "Romantiek"] },
    "Paddington in Peru": { year: 2024, lang: "Engels", country: "VK", duration: 100, genres: ["Animatie", "Avontuur", "Komedie"] },
    "Perfect Days": { year: 2023, lang: "Japans", country: "Japan", duration: 125, genres: ["Drama"] },
    "Skyfall": { year: 2012, lang: "Engels", country: "VK", duration: 143, genres: ["Actie", "Avontuur", "Thriller"] },
    "Sweet Dreams": { year: 2023, lang: "Nederlands", country: "Nederland", duration: 102, genres: ["Drama"] },
    "Thank You for Banking with Us": { year: 2024, lang: "Arabisch, Engels", country: "Palestina", duration: 92, genres: ["Drama"] },
    "The Adventures of Baron Munchausen": { year: 1988, lang: "Engels", country: "VK", duration: 126, genres: ["Avontuur", "Komedie", "Fantasy"] },
    "The Baltimorons": { year: 2025, lang: "Engels", country: "VS", duration: 99, genres: ["Romantische komedie"] },
    "The Devil Wears Prada": { year: 2006, lang: "Engels", country: "VS", duration: 109, genres: ["Komedie", "Drama"] },
    "The Fish Fall in Love": { year: 2006, lang: "Perzisch", country: "Iran", duration: 95, genres: ["Drama", "Romantiek"]},
    "The Grand Budapest Hotel": { year: 2014, lang: "Engels", country: "VS", duration: 99, genres: ["Avontuur", "Komedie", "Drama"] },
    "The Life Aquatic with Steve Zissou": { year: 2004, lang: "Engels", country: "VS", duration: 119, genres: ["Avontuur", "Komedie", "Drama"] },
    "The Proposal": { year: 2009, lang: "Engels", country: "VS", duration: 108, genres: ["Komedie", "Drama", "Romantiek"] },
    "The Salt Path": { year: 2024, lang: "Engels", country: "VK", duration: 112, genres: ["Drama"]},
    "The Secret Life of Walter Mitty": { year: 2013, lang: "Engels", country: "VS", duration: 114, genres: ["Avontuur", "Komedie", "Drama"] },
    "The Terminal": { year: 2004, lang: "Engels", country: "VS", duration: 128, genres: ["Komedie", "Drama", "Romantiek"] },
    "The Terminator": { year: 1984, lang: "Engels", country: "VS", duration: 107, genres: ["Actie", "Sci-Fi"] },
    "Thelma & Louise": { year: 1991, lang: "Engels", country: "VS", duration: 130, genres: ["Avontuur", "Misdaad", "Drama"] },
    "There Will Be Blood": { year: 2007, lang: "Engels", country: "VS", duration: 158, genres: ["Drama"]},
    "Time of the Gypsies": { year: 1988, lang: "Servokroatisch", country: "Joegoslavië", duration: 142, genres: ["Komedie", "Misdaad", "Drama"]},
    "Top Gun: Maverick": { year: 2022, lang: "Engels", country: "VS", duration: 130, genres: ["Actie", "Drama"] },
    "Up": { year: 2009, lang: "Engels", country: "VS", duration: 96, genres: ["Animatie", "Avontuur", "Komedie"] },
    "Vicky Cristina Barcelona": { year: 2008, lang: "Engels", country: "VS", duration: 96, genres: ["Komedie", "Drama", "Romantiek"] },
    "What Does That Nature Say to You?": { year: 2025, lang: "Koreaans", country: "Zuid-Korea", duration: 108, genres: ["Komedie", "Drama", "Romance"] },
    "When Harry Met Sally...": { year: 1989, lang: "Engels", country: "VS", duration: 95, genres: ["Komedie", "Drama", "Romantiek"] },
};

const events = [
    {
        "id": "hart-museum",
        "title": "Movies at H'ART Museum",
        "period": "6 - 26 augustus 2025",
        "month": ["august"],
        "price": "paid",
        "ticketPrice": "€14 - €17",
        "district": "Centrum",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Engels", "subtitles": "Nederlands" },
        "location": "Binnentuin H'ART Museum, Nieuwe Keizersgracht 1, Amsterdam",
        "coords": { "latitude": 52.3639, "longitude": 4.9022 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=H'ART+Museum+Amsterdam",
        "description": "De grootste openluchtbioscoop van Amsterdam, gesitueerd in de majestueuze en sfeervolle binnentuin van het H'ART Museum. De sfeer is romantisch en stijlvol, perfect voor een avond wegdromen bij geliefde filmklassiekers. Elke voorstelling begint met een legendarische filmquiz en een korte inleiding.",
        "website": "https://www.hartmuseum.nl/activiteiten/movies-hart-museum/",
        "ticketLink": "https://www.moviesathartmuseum.nl/tickets/",
        "imageUrl": "https://www.hartmuseum.nl/wp-content/uploads/2024/05/Movies-2023-768x511.jpg",
        "imageGallery": [
            "https://www.hartmuseum.nl/wp-content/uploads/2024/05/Bora-bora-productions-Movies-at-the-Hermitage-3-1024x683.jpg",
            "https://www.hartmuseum.nl/wp-content/uploads/2024/05/Bora-bora-productions-Movies-at-the-Hermitage-2-768x512.jpg",
            "https://www.hartmuseum.nl/wp-content/uploads/2024/05/Bora-bora-productions-Movies-at-the-Hermitage-768x512.jpg"
        ],
        "program": [
            { "date": "6 aug", "title": "Vicky Cristina Barcelona", "imdb": "tt0497465" },
            { "date": "7 aug", "title": "Fantastic Mr. Fox", "imdb": "tt0432283" },
            { "date": "8 aug", "title": "10 Things I Hate About You", "imdb": "tt0147800" },
            { "date": "9 aug", "title": "Kneecap", "imdb": "tt27552979" },
            { "date": "10 aug", "title": "Lost in Translation", "imdb": "tt0335266" },
            { "date": "11 aug", "title": "On the Road", "imdb": "tt0337692" },
            { "date": "13 aug", "title": "Up", "imdb": "tt1049413" },
            { "date": "14 aug", "title": "Dirty Dancing", "imdb": "tt0092890" },
            { "date": "15 aug", "title": "Ja Zuster, Nee Zuster", "imdb": "tt0309725" },
            { "date": "16 aug", "title": "Challengers", "imdb": "tt16426418" },
            { "date": "17 aug", "title": "Perfect Days", "imdb": "tt27503384" },
            { "date": "18 aug", "title": "7 Years in Tibet", "imdb": "tt0120102" },
            { "date": "20 aug", "title": "Do the Right Thing", "imdb": "tt0097216" },
            { "date": "21 aug", "title": "No Country for Old Men", "imdb": "tt0477348" },
            { "date": "22 aug", "title": "The Secret Life of Walter Mitty", "imdb": "tt0359950" },
            { "date": "23 aug", "title": "Top Gun: Maverick", "imdb": "tt1745960" },
            { "date": "25 aug", "title": "Into the Wild", "imdb": "tt0758758" },
            { "date": "26 aug", "title": "Thelma & Louise", "imdb": "tt0103074" }
        ],
        "extras": ["Bij regen worden er poncho's uitgedeeld.", "Art Movie Mondays hebben een speciale focus op kunstfilms."]
    },
    {
        "id": "pluk-de-nacht",
        "title": "Pluk de Nacht",
        "period": "20 - 30 augustus 2025",
        "month": ["august"],
        "price": "paid",
        "ticketPrice": "€11 (stoel)",
        "district": "Centrum",
        "startTime": "21:30",
        "languageDetails": { "spoken": "Divers (meestal Engels)", "subtitles": "Engels" },
        "location": "Het Stenen Hoofd, Westerdoksdijk, Amsterdam",
        "coords": { "latitude": 52.3890, "longitude": 4.8910 },
        "gmaps": "https://maps.app.goo.gl/74xQ2b4u9kjDg9D59",
        "description": "Het belangrijkste onafhankelijke openluchtfilmfestival van Nederland op een rauwe, industriële stadspier aan het IJ. De programmering is tegendraads en richt zich op films (speelfilms, docu's, shorts) die de reguliere bioscoop vaak niet halen.",
        "website": "https://plukdenacht.nl/",
        "ticketLink": "https://plukdenacht.nl/",
        "imageUrl": "https://plukdenacht.nl/wp-content/uploads/2023/09/Pluk-de-Nacht-2023-79981-1-scaled.jpg",
        "imageGallery": [
            "https://image.parool.nl/220058609/width/1280/pluk-de-nacht-bij-het-stenen-hoofd-in-west",
            "https://plukdenacht.nl/wp-content/uploads/2023/09/Pluk-de-Nacht-2023-1362-1-1024x768.jpg",
            "https://plukdenacht.nl/wp-content/uploads/2023/08/everbruggen_20230826_web_25-1024x683.jpg"
        ],
        "program": [
            { "date": "20 aug (13:00)", "title": "Randprogramma: Intocht Sail", "description": "Vanwege Sail gaan we vandaag eerder open, en je kunt ’s middags al een strandstoel huren om van de bootjes te genieten." },
            { "date": "20 aug (21:30)", "title": "Short: Candy Bar", "description": "In de bioscoop krijgt een man van een meisje te horen dat hij op haar vader lijkt." },
            { "date": "20 aug (21:30)", "title": "A Bright Future", "imdb": "tt27989338", "description": "Een dystopische wereld waar wel cassettebandjes zijn, maar geen dieren meer." },
            { "date": "21 aug", "title": "What Does That Nature Say to You?", "imdb": "tt32039328", "description": "Een dolende dichter, een huis met kippen, en een ontmoeting met de schoonfamilie." },
            { "date": "22 aug (19:15)", "title": "Binnenfilm: Life of Pi", "imdb": "tt0454876", "description": "Een jongen, een tijger, een reddingsboot – en een verhaal dat je kijk op waarheid voorgoed verandert." },
            { "date": "22 aug", "title": "100 Litres of Gold", "imdb": "tt31355431", "description": "Twee zussen moeten met een kater en tegen de klok nieuwe liters bier brouwen om een familiedrama te voorkomen." },
            { "date": "23 aug (19:15)", "title": "Binnenfilm: The Life Aquatic with Steve Zissou", "imdb": "tt0362270", "description": "Een zeldzame haai, een verloren vriend en een mislukte oceaanheld op wraaktocht." },
            { "date": "23 aug", "title": "Brother Verses Brother", "imdb": "tt27534531", "description": "Twee broers zoeken hun 99-jarige vader in San Francisco – zingend, ruziënd en improviserend." },
            { "date": "24 aug (14:00)", "title": "Pluk MINI (kindereditie)", "description": "Een paradijs voor kleine avonturiers met Popeye op het grote doek, bootjes bouwen en de legendarische Pluk MINI disco." },
            { "date": "24 aug", "title": "Kontinental ’25", "imdb": "tt31840813", "description": "Een gerechtsdeurwaarder worstelt met haar schuldgevoel in een messcherpe satire over het kapitalisme." },
            { "date": "25 aug", "title": "Bitter Gold", "imdb": "tt29524741", "description": "Een spannende Chileense western over overleven, loyaliteit en de prijs van hebzucht." },
            { "date": "26 aug", "title": "A Vida Luminosa", "imdb": "tt31835331", "description": "Een warme, lichte film over de mooie chaos van jong-volwassen zijn in Lissabon." },
            { "date": "27 aug", "title": "Thank You for Banking with Us", "imdb": "tt28424264", "description": "Twee zussen proberen met een list hun erfenis veilig te stellen in een schrijnend én geestig kat-en-muisspel." },
            { "date": "28 aug", "title": "Shorts Night!", "description": "Een avondvullend programma met korte films over het menselijk lichaam en alles wat daarbij komt kijken." },
            { "date": "29 aug (19:15)", "title": "Binnenfilm: Billy Elliot", "imdb": "tt0249462", "description": "Een hartverwarmend coming-of-ageverhaal over dromen, moed en het doorbreken van verwachtingen." },
            { "date": "29 aug", "title": "The Baltimorons", "imdb": "tt31128189", "description": "Een ex-standupper en een noodtandarts vinden elkaar tijdens een lange Kerstavond in Baltimore." },
            { "date": "30 aug (19:15)", "title": "Binnenfilm: Little Miss Sunshine", "imdb": "tt0449059", "description": "Een chaotische roadtrip van een gestoorde familie verandert in een hartverwarmend verhaal." },
            { "date": "30 aug", "title": "Fwends", "imdb": "tt32319086", "description": "Twee GenZ-vriendinnen van vroeger zien elkaar weer terug in Melbourne, met totaal geïmproviseerde gesprekken." }
        ],
        "extras": ["Terrein is gratis toegankelijk, je betaalt voor een strandstoel.", "Na de film is er 'De Stille Nachtclub' om te dansen."]
    },
    {
        "id": "west-beach",
        "title": "West Beach Film Festival",
        "period": "17 - 21 september 2025",
        "month": ["september"],
        "price": "free",
        "ticketPrice": "Gratis",
        "district": "Nieuw-West",
        "startTime": "20:30",
        "languageDetails": { "spoken": "Nederlands/Engels", "subtitles": "Nederlands/Engels" },
        "location": "Buurtwerkplaats Noorderhof, Sloterplas",
        "coords": { "latitude": 52.3687, "longitude": 4.8037 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Buurtwerkplaats+Noorderhof+Sloterplas",
        "description": "Een gratis, vijfdaags evenement aan de oevers van de Sloterplas. Meer dan alleen film; een viering van de buurt met muziek, kunst, workshops en gezamenlijke maaltijden. Het thema voor 2025 is 'HABITAT'.",
        "website": "https://westbeachfilmfestival.com/",
        "ticketLink": null,
        "imageUrl": "https://storage.pubble.nl/648e3015/content/2022/6/183dbfe6-97fa-4cff-8169-ff4e358cf8d6_thumb1920.jpg",
        "imageGallery": [
            "https://app.thefeedfactory.nl/api/assets/6878c7f77c674714bad23b56/west_beach_film_festival.jpg",
            "https://app.thefeedfactory.nl/api/assets/65aa91c28a54014acca58517/Ontwerp_zonder_titel.jpg",
            "https://image.parool.nl/221621106/width/1280/west-beach-film-festival-in-nieuw-west"
        ],
        "program": [
            { "date": "17 sep", "title": "Anora", "imdb": "tt29298482" },
            { "date": "18 sep", "title": "Sweet Dreams", "imdb": "tt21223406" },
            { "date": "19 sep", "title": "Skyfall", "imdb": "tt1074638" },
            { "date": "20 sep", "title": "Paddington in Peru", "imdb": "tt2262245" },
            { "date": "21 sep", "title": "Time of the Gypsies", "imdb": "tt0097223" }
        ],
        "extras": ["Toegang is gratis (pay-as-you-like).", "Vaak vergezeld van live DJ-sets en workshops."]
    },
    {
        "id": "cinetree",
        "title": "Cinetree Forest Film Festival",
        "period": "14 - 17 augustus 2025",
        "month": ["august"],
        "price": "paid",
        "ticketPrice": "€15",
        "district": "Zuid",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Engels", "subtitles": "Nederlands" },
        "location": "Amsterdamse Bostheater, Amsterdamse Bos",
        "coords": { "latitude": 52.3297, "longitude": 4.8385 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Amsterdamse+Bostheater",
        "description": "Een magische filmervaring in het Amsterdamse Bostheater. Het festival combineert filmvertoningen onder de sterrenhemel met muziek, poëzie en inleidingen van experts voor een diepere beleving.",
        "website": "https://bostheater.nl/ons-programma/cinetree/",
        "ticketLink": "https://bostheater.nl/ons-programma/cinetree/",
        "imageUrl": "https://media.iamsterdam.com/w_907,h_514/1xdpg3tii444-cinetree-forest-film-festival.webp",
        "imageGallery": [
            "https://media.iamsterdam.com/w_907,h_514/4644yllu7ljt-cinetree-forest-film-festival1.webp",
            "https://media.iamsterdam.com/w_907,h_514/4tbr3ce4udax-cinetree-forest-film-festival.webp",
            "https://image.parool.nl/206989192/width/2480/dit-weekend-vindt-het-forest-film-festival-plaats"
        ],
        "program": [
            { "date": "14 aug", "title": "The Salt Path", "imdb": "tt13632948" },
            { "date": "15 aug", "title": "Do the Right Thing", "imdb": "tt0097216" },
            { "date": "16 aug", "title": "Lion", "imdb": "tt3741834" },
            { "date": "17 aug", "title": "Flow", "imdb": "tt22513420" }
        ],
        "extras": ["Op 17 augustus is de 'Cinetree Dog Night', honden zijn dan welkom!", "Niet te verwarren met 'Bosbios', wat in Hilversum plaatsvindt."]
    },
     {
        "id": "pllek",
        "title": "Films with a View bij Pllek",
        "period": "Elke dinsdag t/m september",
        "month": ["august", "september"],
        "price": "paid",
        "ticketPrice": "€10",
        "district": "Noord",
        "startTime": "22:00",
        "languageDetails": { "spoken": "Engels", "subtitles": "Geen (koptelefoon)" },
        "location": "Pllek, NDSM-werf, Amsterdam",
        "coords": { "latitude": 52.3992, "longitude": 4.8931 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Pllek+Amsterdam",
        "description": "Elke dinsdagavond transformeert het stadsstrand aan de NDSM-werf in een bioscoop met een adembenemend uitzicht op de skyline. Geniet met je voeten in het zand en een koptelefoon op van diverse films.",
        "website": "https://pllek.nl/films-with-a-view/",
        "ticketLink": "https://pllek.nl/agenda/",
        "imageUrl": "https://media.iamsterdam.com/w_907,h_514/71760w5du15s-pllek-8.webp",
        "imageGallery": [
            "https://outdoorcinema.nl/wp-content/uploads/2024/04/LOOK-OUT-3-9-van-95-e1689325680338-2-e1713877945687.jpg",
            "https://image.volkskrant.nl/109924345/feature-crop/1200/1200/lekker-chillen-en-genieten-van-een-filmpje-bij-pllek",
            "https://www.bartsboekje.com/wp-content/smush-webp/2024/07/Scherm%C2%ADafbeelding-2024-07-04-om-18.30.28-600x332.png.webp"
        ],
        "program": [
            { "date": "5 aug", "title": "The Adventures of Baron Munchausen", "imdb": "tt0096764" },
            { "date": "12 aug", "title": "La Chimera", "imdb": "tt14561712" },
            { "date": "19 aug", "title": "Amsterdam", "imdb": "tt10304142" },
            { "date": "26 aug", "title": "There Will Be Blood", "imdb": "tt0469494" }
        ],
        "extras": ["De vertoning is afhankelijk van het weer. Rond 13:00 op de dag zelf wordt gecommuniceerd of het doorgaat."]
    },
    {
        "id": "bijlmerbios",
        "title": "Bijlmerbios Openluchtbios",
        "period": "22, 23 aug & 13 sep",
        "month": ["august", "september"],
        "price": "free",
        "ticketPrice": "Gratis",
        "district": "Zuidoost",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Nederlands/Engels", "subtitles": "Nederlands/Engels" },
        "location": "Diverse locaties in Amsterdam Zuidoost",
        "coords": { "latitude": 52.3198, "longitude": 4.9609 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=metrostation+Kraaiennest+amsterdam",
        "description": "Een unieke, gratis filmervaring op kenmerkende locaties in Amsterdam Zuidoost. De filmvertoningen worden omlijst door evenementen die de hele dag duren, zoals een Skate Board Jam en een Street Art Jam.",
        "website": "https://bijlmerbios.com/openluchtbios/",
        "ticketLink": null,
        "imageUrl": "https://app.thefeedfactory.nl/api/assets/665d8a955fbf84055a63e343/Bijlmerbios_2-__Hans_Mooren-Uitkrant.webp",
        "imageGallery": [
            "https://www.amsterdamsfondsvoordekunst.nl/site/assets/files/11155/bijlmerbios.1280x0.jpg",
            "https://bijlmerbios.com/wp-content/uploads/2019/07/Bijlmerbios-2017-4-%C2%A9-Bas-Bakkenes.jpg",
            "https://image.parool.nl/220825337/width/1280/de-bijlmerbios-in-zuidoost"
        ],
        "program": [
            { "date": "22 aug", "title": "One of Them Days", "imdb": null },
            { "date": "23 aug", "title": "Straatcoaches vs Aliens", "imdb": null },
            { "date": "13 sep", "title": "In the Heights", "imdb": "tt1319627" }
        ],
        "extras": ["De evenementen zijn volledig gratis toegankelijk.", "Er zijn uitgebreide voorprogramma's met o.a. skaten, street art en dans."]
    },
    {
        "id": "nemo",
        "title": "NEMO Film op het Dak",
        "period": "28 - 30 augustus 2025",
        "month": ["august"],
        "price": "paid",
        "ticketPrice": "€15",
        "district": "Centrum",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Italiaans", "subtitles": "Engels" },
        "location": "Dakterras NEMO, Oosterdok 2, Amsterdam",
        "coords": { "latitude": 52.3745, "longitude": 4.9123 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=NEMO+Science+Museum+Amsterdam",
        "description": "Het vernieuwde dakterras van NEMO, ontworpen als een Italiaanse 'piazza', vormt het decor voor een speciaal filmweekend. Drie avonden lang worden hier Italiaanse filmklassiekers vertoond, met een spectaculair uitzicht over de stad.",
        "website": "https://www.nemosciencemuseum.nl/",
        "ticketLink": "https://www.nemosciencemuseum.nl/",
         "imageUrl": "https://cdn.sanity.io/images/49fr30wg/production/202a13df90aea98eeb3af744e79b2bf2227c6c2c-5657x3771.jpg?rect=0,295,5657,3182&w=1920&h=1080&fit=crop&auto=format",
        "imageGallery": [
            "https://image.parool.nl/234690342/width/1280/films-op-het-dak-bij-nemo-in-centrum",
            "https://www.amsterdamsdagblad.nl/image/55574_107098_1200_1200.webp",
            "https://verkeersbureaus.info/wp-content/uploads/2019/08/nemo-zomerdak-filmavond-2-foto-digidaan.jpg"
        ],
        "program": [
            { "date": "28 aug", "title": "La vita è bella", "imdb": "tt0118799" },
            { "date": "29 aug", "title": "Caro Diario", "imdb": "tt0109382" },
            { "date": "30 aug", "title": "Gloria!", "imdb": "tt29003323" }
        ],
        "extras": ["Geniet van een uniek uitzicht over de stad tijdens de film."]
    },
    {
        "id": "secret-garden",
        "title": "Secret Garden Cinema",
        "period": "22 aug - 13 sep 2025",
        "month": ["august", "september"],
        "price": "paid",
        "ticketPrice": "€12.50",
        "district": "Nieuw-West",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Divers", "subtitles": "Engels" },
        "location": "Binnentuin Cinema de Vlugt, Amsterdam",
        "coords": { "latitude": 52.3792, "longitude": 4.8329 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Cinema+de+Vlugt+Amsterdam",
        "description": "Een intieme openluchtbioscoop in de binnentuin van Cinema De Vlugt. Het programma richt zich op klassiekers uit Turkije, Iran, Egypte en Bollywood, wat een unieke kijkervaring biedt.",
        "website": "https://www.cinemadevlugt.nl/secretgardencinema/",
        "ticketLink": "https://www.cinemadevlugt.nl/secretgardencinema/",
        "imageUrl": "https://app.thefeedfactory.nl/api/assets/68626776df6f7f1272a67ec0/SC_CDV_2.webp",
        "imageGallery": [],
        "program": [
            { "date": "22 aug", "title": "Kabhi Khushi Kabhie Gham", "imdb": "tt0248126" },
            { "date": "23 aug", "title": "The Fish Fall in Love", "imdb": "tt0467597" },
            { "date": "29 aug", "title": "Fatma", "imdb": "tt0052806" },
            { "date": "30 aug", "title": "Hababam Sınıfı", "imdb": "tt0252487" }
        ],
        "extras": ["Richt zich specifiek op wereldcinema voor een unieke culturele ervaring."]
    },
    {
        "id": "cityscape-arena",
        "title": "Cityscape Cinema @ Hotel Arena",
        "period": "5 - 22 augustus 2025",
        "month": ["august"],
        "price": "paid",
        "ticketPrice": "€18.50",
        "district": "Oost",
        "startTime": "21:00 / 21:30",
        "languageDetails": { "spoken": "Engels", "subtitles": "Nederlands (indien aangegeven)" },
        "location": "Hotel Arena, 's-Gravesandestraat 55, Amsterdam",
        "coords": { "latitude": 52.3620, "longitude": 4.9155 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Hotel+Arena+Amsterdam",
        "description": "Films op een unieke daklocatie met comfortabele zitplaatsen. Het programma omvat publieksfavorieten zoals romantische komedies, Disney, actie en sciencefiction.",
        "website": "https://cityscapecinema.com/",
        "ticketLink": "https://shop.ticketapp.com/hggzc",
        "imageUrl": "https://media.iamsterdam.com/w_907,h_514/6ed3afnxw1c5-untitled-design-3.webp",
        "imageGallery": [
            "https://cdn.prod.website-files.com/6572d6e8f828190dadefbcac/657322ac54a49db42228f80b_rooftop-movie-nights.webp",
            "https://hotelarena.nl/wp-content/uploads/Rooftop-Movie-Nights-Hotel-Arena-99-1200x1800.jpg"
        ],
        "program": [
            { "date": "5 aug", "title": "A Man Called Otto", "imdb": "tt7405458" },
            { "date": "6 aug", "title": "About a Boy", "imdb": "tt0276751" },
            { "date": "7 aug", "title": "The Devil Wears Prada", "imdb": "tt0458352" },
            { "date": "8 aug", "title": "Notting Hill", "imdb": "tt0125439" },
            { "date": "9 aug", "title": "La La Land", "imdb": "tt3783958" },
            { "date": "10 aug", "title": "Amélie", "imdb": "tt0211915" },
            { "date": "11 aug", "title": "Notting Hill", "imdb": "tt0125439" },
            { "date": "13 aug", "title": "The Terminal", "imdb": "tt0362227" },
            { "date": "14 aug", "title": "Bohemian Rhapsody", "imdb": "tt1727824" },
            { "date": "15 aug", "title": "Catch Me If You Can", "imdb": "tt0264464" },
            { "date": "16 aug", "title": "The Proposal", "imdb": "tt1041829" },
            { "date": "17 aug", "title": "Mrs. Doubtfire", "imdb": "tt0107614" },
            { "date": "18 aug", "title": "Midnight in Paris", "imdb": "tt1605783" },
            { "date": "19 aug", "title": "The Grand Budapest Hotel", "imdb": "tt2278388" },
            { "date": "20 aug", "title": "Life of Pi", "imdb": "tt0454876" },
            { "date": "21 aug", "title": "Green Book", "imdb": "tt6966692" },
            { "date": "22 aug", "title": "Mamma Mia!", "imdb": "tt0795421" }
        ],
        "extras": ["Ticketprijs is €17.50 excl. €1.00 service fee.", "Starttijd is 21:30 t/m 17 aug, daarna 21:00."]
    },
    {
        "id": "cityscape-leonardo",
        "title": "Cityscape Cinema @ Leonardo Rooftop",
        "period": "18 - 24 augustus 2025",
        "month": ["august"],
        "price": "paid",
        "ticketPrice": "€18.50",
        "district": "Nieuw-West",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Engels", "subtitles": "Nederlands (indien aangegeven)" },
        "location": "Leonardo Hotel Rembrandtpark, Staalmeesterslaan 410, Amsterdam",
        "coords": { "latitude": 52.3615, "longitude": 4.8425 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Leonardo+Hotel+Rembrandtpark",
        "description": "Films op een unieke daklocatie met comfortabele zitplaatsen en een prachtig uitzicht over de stad. Het programma omvat publieksfavorieten zoals romantische komedies, Disney, actie en sciencefiction.",
        "website": "https://cityscapecinema.com/",
        "ticketLink": "https://shop.ticketapp.com/hggzc",
        "imageUrl": "https://scontent.fein1-1.fna.fbcdn.net/v/t1.6435-9/119844250_2704961783048814_8035016743385143717_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=833d8c&_nc_ohc=zwMhh8yNBCgQ7kNvwFIlZ50&_nc_oc=AdlCcmTNhOCSJp8zOnn8vEAHhofiLuCaKid2ypErDGcg6yE-3FKgMB-E8nKVnCZk3lI&_nc_zt=23&_nc_ht=scontent.fein1-1.fna&_nc_gid=QC1QIqojeaZHtlZYtf0UoQ&oh=00_AfW1PGdAC93nM7GlDbgbccFQNOa3zg3-QU0amPFYbDmfXg&oe=68BD60E0",
        "imageGallery": [
            "https://vanduijnenhoreca.nl/wp-content/uploads/sites/2/2021/11/Floor17-rooftop-Amsterdam-e1714130528370.jpg",
            "https://www.yourlittleblackbook.me/wp-content/uploads/2017/08/openlucht-bioscopen-amsterdam-rooftop.jpg"
        ],
        "program": [
            { "date": "18 aug", "title": "Grease", "imdb": "tt0077631" },
            { "date": "19 aug", "title": "Life of Pi", "imdb": "tt0454876" },
            { "date": "20 aug", "title": "Midnight in Paris", "imdb": "tt1605783" },
            { "date": "21 aug", "title": "Interstellar", "imdb": "tt0816692" },
            { "date": "22 aug", "title": "Mean Girls", "imdb": "tt0377092" },
            { "date": "23 aug", "title": "Forrest Gump", "imdb": "tt0109830" },
            { "date": "24 aug", "title": "Bridget Jones's Diary", "imdb": "tt0243155" }
        ],
        "extras": ["Ticketprijs is €17.50 excl. €1.00 service fee."]
    },
    {
        "id": "sunsets-eye",
        "title": "Sunsets at EYE",
        "period": "Zomer 2025",
        "month": ["june", "july", "august"],
        "price": "free",
        "ticketPrice": "Gratis",
        "district": "Noord",
        "startTime": "22:00",
        "languageDetails": { "spoken": "Divers", "subtitles": "Engels" },
        "location": "Park naast het EYE Filmmuseum, IJpromenade 1, Amsterdam",
        "coords": { "latitude": 52.3847, "longitude": 4.9016 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=EYE+Filmmuseum+Amsterdam",
        "description": "Geniet van filmklassiekers en nieuwe ontdekkingen op een groot scherm in het park naast het iconische EYE Filmmuseum, met uitzicht op het IJ. Een perfecte zomeravond met vrienden.",
        "website": "https://www.eyefilm.nl/sunsets",
        "ticketLink": null,
        "imageUrl": "https://app.thefeedfactory.nl/api/assets/668fa028309aba0f1761b5d5/Sunsets_2023_credits_Jordi_Wallenburg__34_.jpg",
        "imageGallery": [
            "https://assets.eyefilm.nl/images/programme-item/_1200x630_crop_center-center_none/campagnebeeld-Sunsets-horizontaal.jpg",
            "https://likealocalguide.com/_next/image?url=https%3A%2F%2Fdirectus.likealocalguide.com%2Fassets%2F47798106-328c-4818-8a0f-b71049814125&w=3840&q=75",
            "https://www.bartsboekje.com/wp-content/smush-webp/2024/07/Scherm%C2%ADafbeelding-2024-07-04-om-17.56.42-600x420.png.webp"
        ],
        "program": [
            { "date": "Nog niet bekend", "title": "Programma wordt later aangekondigd", "imdb": null }
        ],
        "extras": ["Gratis toegang, neem je eigen kleedje mee."]
    },
    {
        "id": "moons-of-cavia",
        "title": "Moons of Cavia @ Filmhuis Cavia",
        "period": "28 - 31 augustus 2025",
        "month": ["august"],
        "price": "free",
        "ticketPrice": "Donatie (Cineville geldig)",
        "district": "West",
        "startTime": "20:00 (deuren open)",
        "languageDetails": { "spoken": "Divers", "subtitles": "Engels" },
        "location": "Tuin Filmhuis Cavia, Van Hallstraat 52, Amsterdam",
        "coords": { "latitude": 52.3781, "longitude": 4.8681 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Van+Hallstraat+52+Amsterdam",
        "description": "Het kleinste filmhuis van Amsterdam gaat naar buiten! In de intieme tuin van Filmhuis Cavia geniet je van een eigenzinnig en verrassend programma onder de sterrenhemel. Een unieke, lokale filmervaring.",
        "website": "https://filmhuiscavia.nl/",
        "ticketLink": "https://filmhuiscavia.nl/programma/",
        "imageUrl": "https://www.filmhuiscavia.nl/application/files/2216/9020/8392/moons-2023-kaboom.jpg",
        "imageGallery": [
            "https://filmhuiscavia.nl/application/files/3916/9020/8393/moons-2023-zienema2.jpg",
            "https://filmhuiscavia.nl/application/files/2917/5371/1843/Moons-Poster-2025.png",
            "https://www.filmhuiscavia.nl/application/files/6816/2489/1421/binnentuin-kasparhauser_.jpg"
        ],
        "program": [
            { "date": "28-31 aug", "title": "Programma via de website", "imdb": null }
        ],
        "extras": ["Toegang op donatiebasis.", "Cinevillepas is geldig."]
    },
    {
        "id": "panorama-nights-lab111",
        "title": "Panorama Movie Nights @ Oedipus Craft Space",
        "period": "Woensdagen in juli & aug",
        "month": ["july", "august"],
        "price": "paid",
        "ticketPrice": "€8 (incl. biertje)",
        "district": "Noord",
        "startTime": "21:00",
        "languageDetails": { "spoken": "Engels", "subtitles": "Nederlands" },
        "location": "Oedipus Craft Space, Schaafstraat 21, Amsterdam",
        "coords": { "latitude": 52.3916, "longitude": 4.9221 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Oedipus+Craft+Space+Schaafstraat+21+Amsterdam",
        "description": "LAB111 en Oedipus Brewing slaan de handen ineen voor Panorama Nights. Geniet van een gecureerde selectie films in de relaxte sfeer van de Oedipus Craft Space, inclusief een speciaal Panorama biertje.",
        "website": "https://www.lab111.nl/lab111-oedipus-brewing-present-panorama-movie-nights/",
        "ticketLink": "https://shop.lab111.nl/",
        "imageUrl": "https://oedipus.com/cdn/shop/files/IMG_8232.jpg?v=1752157019&width=750",
        "imageGallery": [
            "https://www.lab111.nl/wp-content/uploads/2025/07/image001.png",
            "https://www.yourlittleblackbook.me/wp-content/uploads/2024/10/Oedipus-Craft-Space-Amsterdam-3-marinachef-.jpg"
        ],
        "program": [
            { "date": "10 jul", "title": "Do the Right Thing", "imdb": "tt0097216" },
            { "date": "17 jul", "title": "Ghost In The Shell", "imdb": "tt0113568" },
            { "date": "24 jul", "title": "The Terminator", "imdb": "tt0088247" },
            { "date": "31 jul", "title": "Her", "imdb": "tt1798709" },
            { "date": "7 aug", "title": "Ex Machina", "imdb": "tt0470752" },
            { "date": "14 aug", "title": "When Harry Met Sally...", "imdb": "tt0098635" }
        ],
        "extras": ["Ticket is inclusief een Oedipus Panorama biertje.", "Samenwerking tussen LAB111 en Oedipus Brewing."]
    },
    {
        "id": "cinema-amstelveen-tour",
        "title": "Cinema Amstelveen on Tour",
        "period": "5, 6, 12 & 13 september",
        "month": ["september"],
        "price": "free",
        "ticketPrice": "Gratis (verwacht)",
        "district": "Zuid",
        "startTime": "20:30",
        "languageDetails": { "spoken": "Nederlands/Engels", "subtitles": "Nederlands" },
        "location": "Diverse locaties in Amstelveen",
        "coords": { "latitude": 52.3023, "longitude": 4.8453 },
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Schouwburg+Amstelveen",
        "description": "Cinema Amstelveen trekt eropuit! Geniet van gratis filmvertoningen op verschillende pleinen in Amstelveen, zoals het Stadsplein en het plein bij Theater De Landing. Een gezellig filmevenement voor de hele buurt.",
        "website": "https://schouwburgamstelveen.nl/nl/pinfo/2324090/cinema-on-tour",
        "ticketLink": null,
        "imageUrl": "https://www.mijnamstelveen.nl/current/local/runtime/images/17410/1120x630/IMG_1462.jpeg",
        "imageGallery": [
            "https://schouwburgamstelveen.nl/media/dx5nff2v/photo-2023-06-30-22-21-58.jpg?anchor=center&mode=crop&width=1436&height=802&rnd=133346681547670000",
            "https://schouwburgamstelveen.nl/media/4c2oqzya/photo-2023-06-30-22-21-55.jpg"
        ],
        "program": [
            { "date": "5 & 6 sep", "title": "Programma volgt (Stadsplein)" },
            { "date": "12 & 13 sep", "title": "Programma volgt (De Landing)" }
        ],
        "extras": ["Gratis toegang.", "Locaties: Stadsplein (5 & 6 sep) en plein bij Theater De Landing (12 & 13 sep)."]
    }
];
